version: '3'

services:
  db:
    image: postgres:10.5
    container_name: djangoplicity-newsletters-db
    restart: always
    environment:
      POSTGRES_DB: djangoplicity-newsletters
      POSTGRES_USER: djangoplicity-newsletters
      POSTGRES_PASSWORD: djangoplicity-newsletters
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: djangoplicity-newsletters-web
    command: ["./scripts/command-dev.sh"]
    volumes:
      - ./djangoplicity:/app/djangoplicity
      - ./test_project/:/app/test_project
      - ./htmlcov:/app/htmlcov
      - ./.coveragerc:/app/.coveragerc
      # - ./tests:/app/tests
    ports:
      - "8001:8000"
    depends_on:
      - db
volumes:
  pgdata: