# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mailinglists', '0003_auto_20170906_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailchimpeventaction',
            name='on_event',
            field=models.CharField(choices=[], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='api_key',
            field=models.CharField(default='', max_length=255, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='avg_sub_rate',
            field=models.IntegerField(blank=True, help_text='per month', null=True),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='avg_unsub_rate',
            field=models.IntegerField(blank=True, help_text='per month', null=True),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='click_rate',
            field=models.IntegerField(blank=True, help_text='per campaign', null=True),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Select the content type of objects that subscribers on this list can be linked with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='open_rate',
            field=models.IntegerField(blank=True, help_text='per campaign', null=True),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='target_sub_rate',
            field=models.IntegerField(blank=True, help_text='per month', null=True),
        ),
        migrations.AlterField(
            model_name='mailchimplisttoken',
            name='uuid',
            field=models.CharField(max_length=36, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='mailchimpmergevar',
            name='field_type',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('text', 'text'), ('number', 'number'), ('radio', 'radio'), ('dropdown', 'dropdown'), ('date', 'date'), ('address', 'address'), ('phone', 'phone'), ('url', 'url'), ('imageurl', 'imageurl')], max_length=20),
        ),
    ]
