# Generated by Django 2.2 on 2020-11-11 22:19

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0011_auto_20201016_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceselector',
            name='filter',
            field=models.CharField(choices=[('I', 'Include'), ('E', 'Exclude')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='datasourceselector',
            name='type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Integer'), ('bool', 'Boolean'), ('date', 'Date'), ('list', 'List')], default='str', max_length=4),
        ),
        migrations.AlterField(
            model_name='mailchimpcampaign',
            name='lang',
            field=djangoplicity.translation.fields.LanguageField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='mailerparameter',
            name='type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Integer'), ('bool', 'Boolean'), ('date', 'Date')], default='str', max_length=4),
        ),
        migrations.AlterField(
            model_name='mailerparameter',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='html',
            field=models.TextField(blank=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='scheduled_status',
            field=models.CharField(choices=[('OFF', 'Not Scheduled'), ('ONGOING', 'Being Scheduled'), ('ON', 'Scheduled')], default='OFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='newsletters.Newsletter', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='newslettertype',
            name='html_template',
            field=models.TextField(blank=True, verbose_name='HTML template'),
        ),
    ]
